name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Make sure this matches your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to the correct folder
            cd /home/ubuntu/Mirkwood-Logistics || exit 1

            # Ensure it's a git repository
            if [ ! -d ".git" ]; then
              echo "ERROR: This is not a git repository!"
              exit 1
            fi

            # Pull latest changes
            git pull origin main

            # Check if docker-compose.yml exists
            if [ ! -f "docker-compose.yml" ]; then
              echo "ERROR: docker-compose.yml is missing!"
              exit 1
            fi

            # Restart application
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
